jieba_dict      /home/you/SearchEngine/third_party/cppjieba/dict/jieba.dict.utf8
jieba_hmm       /home/you/SearchEngine/third_party/cppjieba/dict/hmm_model.utf8
jieba_user      /home/you/SearchEngine/third_party/cppjieba/dict/user.dict.utf8
jieba_idf       /home/you/SearchEngine/third_party/cppjieba/dict/idf.utf8
jieba_stop      /home/you/SearchEngine/third_party/cppjieba/dict/stop_words.utf8

cn_stopwords    /home/you/SearchEngine/corpus/stopwords/cn_stopwords.txt
en_stopwords    /home/you/SearchEngine/corpus/stopwords/en_stopwords.txt

xml_dir         /home/you/SearchEngine/corpus/webpages
en_corpus       /home/you/SearchEngine/corpus/EN/english.txt

ripepage        /home/you/SearchEngine/data/ripepage.dat
offset          /home/you/SearchEngine/data/offset.dat
invert_index    /home/you/SearchEngine/data/invertIndex.dat
dict            /home/you/SearchEngine/data/dict.dat
dict_index      /home/you/SearchEngine/data/dictIndex.dat
